# Generated by Django 2.1.2 on 2018-10-21 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0002_iteminfo_orderinfo'),
        ('rbac', '0002_menu_permission_role_userinfo'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('item', '产品问题'), ('service', '服务问题'), ('advice', '意见建议'), ('other', '其他问题')], default='', max_length=32)),
                ('content', models.TextField()),
                ('reply', models.TextField(blank=True, default='', null=True)),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('processing', '处理中'), ('finished', '已完成')], default='submitted', max_length=32)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply', models.TextField(blank=True, default='', null=True)),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('processing', '处理中'), ('finished', '已完成')], default='submitted', max_length=32)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.OrderInfo')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.UserInfo')),
            ],
        ),
    ]
