# Generated by Django 2.1.2 on 2018-10-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20181021_2201'),
        ('feedback', '0002_complaintinfo_serviceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_customer_id', to='rbac.UserInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_staff_id', to='rbac.UserInfo'),
        ),
    ]
