# Generated by Django 2.1.2 on 2018-10-20 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_menu_permission_role_userinfo'),
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('num', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('production_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('left_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='rbac.UserInfo')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.ItemInfo')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id', to='rbac.UserInfo')),
            ],
        ),
    ]
