# Generated by Django 2.1.2 on 2018-10-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_iteminfo_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
