# Generated by Django 2.1.2 on 2018-10-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customermessage_staffmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerMessage',
            new_name='CustomerInfo',
        ),
        migrations.RenameModel(
            old_name='StaffMessage',
            new_name='StaffInfo',
        ),
    ]
