# Generated by Django 2.1.2 on 2018-10-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181021_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='rate_times',
            field=models.IntegerField(default=1),
        ),
    ]
